const objectarray =
    [
        { name: "Teflon Products Dealer" },
        { name: "3d Theaters" },
        { name: "4d Theaters" },
        { name: "Abacus Classes" },
        { name: "Abrasive Dealers" },
        { name: "Abundant Life Churches" },
        { name: "AC Repairs &Services" },
        { name: "Accommodation" },
        { name: "Acupuncture" },
        { name: "Adhesive" },
        { name: "Adoption Centres" },
        { name: "Adventure Clubs" },
        { name: "Advertising" },
        { name: "Advertising Agencies" },
        { name: "Advocates" },
        { name: "Aerobics" },
        { name: "Aeronautical Engineering Colleges" },
        { name: "Air And Train Ambulance Services" },
        { name: "Air Cargo Agents" },
        { name: "Air Conditioners" },
        { name: "Air Coolers" },
        { name: "Air Hostess Training Institutes" },
        { name: "Air Pollution Control Equipment Dealers" },
        { name: "Alliance Churches" },
        { name: "Alloy, Iron & Steel Industries" },
        { name: "Alternative Fuels Stations" },
        { name: "Alternative Medicines" },
        { name: "Aluminium Extrusion Industry" },
        { name: "Ambulance Services" },
        { name: "Ammonia Gas Dealers" },
        { name: "Amusement Parks" },
        { name: "Anglican Churches" },
        { name: "Animation Training Institutes" },
        { name: "Apostolic Churches" },
        { name: "Apparels & Accessories" },
        { name: "Apple Product Repair" },
        { name: "Aquarium" },
        { name: "Architects" },
        { name: "Area Rugs & Mats" },
        { name: "Armenian Churches" },
        { name: "Arms & Ammunition Dealer" },
        { name: "Arms And Ammunitions" },
        { name: "Art Gallery" },
        { name: "Art Paintings" },
        { name: "Artificial Grass" },
        { name: "Artificial Turf" },
        { name: "Arts & Craft Classes" },
        { name: "Astrologers" },
        { name: "ATM Centres" },
        { name: "Audio Video Systems" },
        { name: "Auditoriums" },
        { name: "Auto Dealers" },
        { name: "Auto Service Centres" },
        { name: "Automobile Engine Oil Dealers" },
        { name: "Automobiles" },
        { name: "Aviation Academies" },
        { name: "Ayurvedic Food" },
        { name: "Ayurvedic Medicines" },
        { name: "Ayurvedic Treatment" },
        { name: "B 2 B" },
        { name: "B Pharmacy Colleges" },
        { name: "B.Ed. Colleges" },
        { name: "Baby Foods" },
        { name: "Baby Store" },
        { name: "Bakeries" },
        { name: "Bakery Equipments" },
        { name: "Balloon Decorations" },
        { name: "Bamboo Flooring" },
        { name: "Bangles" },
        { name: "Banks" },
        { name: "Banquet Halls" },
        { name: "Baptist Churches" },
        { name: "Bar Coding Machine Dealer" },
        { name: "Bars" },
        { name: "Bathroom Linen" },
        { name: "Battery Dealers" },
        { name: "BDS Colleges" },
        { name: "Bean Bags" },
        { name: "Beautician Training Institutes" },
        { name: "Beauty & Wellness" },
        { name: "Beauty And Cosmetic Products" },
        { name: "Beauty Parlours" },
        { name: "Bed Linen" },
        { name: "Bed Room Furniture" },
        { name: "Beef Shops" },
        { name: "Belts & Wallets" },
        { name: "Bicycle Stores" },
        { name: "Bike Rentals" },
        { name: "Billing Machine Dealers" },
        { name: "Binding" },
        { name: "Binoculars & Telescope" },
        { name: "Birth Certificate Offices" },
        { name: "Blocks Material" },
        { name: "Blood Donation Centres" },
        { name: "Blow Moulding Machine Dealer" },
        { name: "Body Massage Parlours" },
        { name: "Boilers" },
        { name: "Book Publishers" },
        { name: "Books Stores" },
        { name: "Bore Well Drilling" },
        { name: "Boutiques" },
        { name: "Bowling" },
        { name: "Brick Materials" },
        { name: "Bridal Makeup" },
        { name: "Budget Hotels" },
        { name: "Building and Construction" },
        { name: "Building Demolition" },
        { name: "Building Materials" },
        { name: "Bulk SMS Modems" },
        { name: "Bulk Sms Services" },
        { name: "Burqa Retailers" },
        { name: "Business Cards" },
        { name: "Business Consultants" },
        { name: "Business Hotels" },
        { name: "CA & ICWA Training Institutes" },
        { name: "Cable Manufacturers" },
        { name: "Cable Tv Operators" },
        { name: "Cabs Services" },
        { name: "Cafes" },
        { name: "Cake Shops" },
        { name: "Calvary Chapel Churches" },
        { name: "Camera Accessories" },
        { name: "Camera Lens" },
        { name: "Cameras" },
        { name: "Candles" },
        { name: "Caps & Hats" },
        { name: "Car Ac Repairs" },
        { name: "Car Accessories" },
        { name: "Car Dealers" },
        { name: "Car Rentals" },
        { name: "Car Repairs & Services" },
        { name: "Carbon Dioxide Gas Dealers" },
        { name: "Cargo & Logistics" },
        { name: "Cargo Agents" },
        { name: "Carpenters" },
        { name: "Carpet & Rugs" },
        { name: "Carpet And Carpet Tiles" },
        { name: "Casual Dining" },
        { name: "Catering Services" },
        { name: "Catholic Churches" },
        { name: "CBSC Schools" },
        { name: "Cement Materials" },
        { name: "Central Government Offices" },
        { name: "Centreing Materials" },
        { name: "Chairs" },
        { name: "Chandeliers" },
        { name: "Charitable Trusts" },
        { name: "Chartered Accountants" },
        { name: "Chartered Bus" },
        { name: "Chat & Snacks" },
        { name: "Chicken Shops" },
        { name: "Children Wear" },
        { name: "Children's Hospitals" },
        { name: "Chimneys" },
        { name: "Chips & Snacks Shops" },
        { name: "Chit Funds" },
        { name: "Chocolate Shops" },
        { name: "Churches" },
        { name: "Cinema Theaters" },
        { name: "Citric Acid Dealers" },
        { name: "City Clerk Offices" },
        { name: "City Government Offices" },
        { name: "Civil Contractors" },
        { name: "Cleaning Tools & Accessories" },
        { name: "Clinics" },
        { name: "Clocks" },
        { name: "Cloud Software" },
        { name: "Clubs" },
        { name: "CNG Pump Stations" },
        { name: "Coarse Aggregates" },
        { name: "Commercial Kitchen Equipment Dealers" },
        { name: "Communication" },
        { name: "Competitive Exams" },
        { name: "Computer Accessories & Peripherals" },
        { name: "Computers" },
        { name: "Computers, Tablets & Mobiles" },
        { name: "Conference Hall" },
        { name: "Construction & Renovation" },
        { name: "Construction Companies" },
        { name: "Consultants" },
        { name: "Contact Lenses" },
        { name: "Content Writers" },
        { name: "Contractors" },
        { name: "Convention Centres" },
        { name: "Cooking Classes" },
        { name: "Cooks On Hire" },
        { name: "Cooktops" },
        { name: "Cookware" },
        { name: "Corporate Catering Services" },
        { name: "Corporate Gifts" },
        { name: "Cosmetic Surgery" },
        { name: "Couriers" },
        { name: "Courts" },
        { name: "CPAP & BIPAP Systems" },
        { name: "Crackers" },
        { name: "Crane Services" },
        { name: "Cremation Grounds" },
        { name: "Cremation Services" },
        { name: "Curtain Accessories" },
        { name: "Cushion & Cushion Covers" },
        { name: "Cutlery" },
        { name: "Dance Academies" },
        { name: "Dead Body Freezer Box On Hire" },
        { name: "Decor & Lightings" },
        { name: "Decor & Show Pieces" },
        { name: "Decoration Materials" },
        { name: "Degree Colleges" },
        { name: "Dental Clinics" },
        { name: "Designing & Wood Carving" },
        { name: "Detective Agencies" },
        { name: "Dhaba" },
        { name: "Diagnostic Centres" },
        { name: "Diesel Gas Stations" },
        { name: "Dietician" },
        { name: "Digital Cameras" },
        { name: "Digital Printers" },
        { name: "Digital Weighing Scale Dealers" },
        { name: "Dining" },
        { name: "Dining Room Furniture" },
        { name: "Dining Sets" },
        { name: "Disc Jockey Training Institutes" },
        { name: "Dishwasher" },
        { name: "Diwan Sets" },
        { name: "Doctors" },
        { name: "Dog Training" },
        { name: "Doors, Windows & Partitions" },
        { name: "Drama Theaters" },
        { name: "Dress Materials" },
        { name: "Drilling Equipments" },
        { name: "Driver Service Agents" },
        { name: "Dry Fruits" },
        { name: "Dry Ice Dealer" },
        { name: "DSLR Cameras" },
        { name: "DTP Services" },
        { name: "Dvd & Vcd" },
        { name: "Eastern Orthodox Churches" },
        { name: "Education" },
        { name: "Education Colleges" },
        { name: "Education Consultants" },
        { name: "Education Councils & Board Offices" },
        { name: "Education Schools" },
        { name: "Egg Shops" },
        { name: "Electrical Contractors" },
        { name: "Electrical Sub-Stations" },
        { name: "Electrical Suppliers" },
        { name: "Electricians" },
        { name: "Electronic Accessories" },
        { name: "Electronic Display Boards Manufacturer" },
        { name: "Electronic Weighing Scale Dealers" },
        { name: "Electronics" },
        { name: "Elevators" },
        { name: "Email Marketing" },
        { name: "Embroidery Works" },
        { name: "Emergency Services" },
        { name: "Engineering Colleges" },
        { name: "ENT Hospitals" },
        { name: "Entrance Exams Coaching Centres" },
        { name: "Establishments" },
        { name: "Ethnic Wear" },
        { name: "Evangelical Churches" },
        { name: "Event Decorators" },
        { name: "Event Management" },
        { name: "Event Organizers" },
        { name: "Event Venues" },
        { name: "Events Catering Services" },
        { name: "Excavation" },
        { name: "Eye Hospitals" },
        { name: "Eyeglasses" },
        { name: "Fabrication & Welding Works" },
        { name: "False Ceiling" },
        { name: "Family Clubs" },
        { name: "Fans" },
        { name: "Farm Houses" },
        { name: "Fashion Designers" },
        { name: "Fashion Designing Training Institutes" },
        { name: "Fast Food Centre" },
        { name: "Fertility & Infertility Clinics" },
        { name: "Fertilizer & Soil" },
        { name: "Film And Television Institute Of India" },
        { name: "Film Studios" },
        { name: "Financial Planners" },
        { name: "Financial Services" },
        { name: "Fine Dining" },
        { name: "Fire Alarms" },
        { name: "Fire And Safety Course Training" },
        { name: "Fire Extinguishers" },
        { name: "Fire Protection Systems" },
        { name: "Fire Safety Equipments" },
        { name: "Fire Stations" },
        { name: "Fish & Sea Food Shops" },
        { name: "Fitness Centres" },
        { name: "Flex Printing Services" },
        { name: "Flooring" },
        { name: "Flooring Installations" },
        { name: "Flooring Tools & Materials" },
        { name: "Florists" },
        { name: "Flower Decorations" },
        { name: "Food & Beverage Outlets" },
        { name: "Food & Beverages" },
        { name: "Food Courts" },
        { name: "Food Machinery Manufacturer" },
        { name: "Food Processing Equipment Manufacturer" },
        { name: "Food Stores" },
        { name: "Footwear" },
        { name: "Foreign Exchange" },
        { name: "Foursquare Churches" },
        { name: "Frames" },
        { name: "Fruit Juice Processing Machine Manufacture" },
        { name: "Fruits" },
        { name: "Full Gospel Churches" },
        { name: "Function Halls" },
        { name: "Funeral Band" },
        { name: "Funeral Materials" },
        { name: "Furnishings" },
        { name: "Furniture" },
        { name: "Furniture on Hire" },
        { name: "Furniture Storage" },
        { name: "Gaming Centres" },
        { name: "Gardening Tools" },
        { name: "Garments" },
        { name: "Gas Dealers" },
        { name: "Gas Stations" },
        { name: "Gemological Institute Of India" },
        { name: "General Hospitals" },
        { name: "General order suppliers" },
        { name: "General Pharmacies" },
        { name: "GI Pipe Dealer" },
        { name: "Gifts And Novelties" },
        { name: "Glass Fitting Hardware" },
        { name: "Glasswares" },
        { name: "Go Karting" },
        { name: "Goldsmiths" },
        { name: "Gospel Churches" },
        { name: "Government Hospitals" },
        { name: "Government Offices" },
        { name: "Graphic Designers" },
        { name: "GRE & TOEFL Coaching Centres" },
        { name: "Greek Orthodox Churches" },
        { name: "Groceries" },
        { name: "Groundwater Surveyors" },
        { name: "Guest Houses" },
        { name: "Gurudwaras" },
        { name: "Gyeser/Water Heater Repair" },
        { name: "Gymnasium" },
        { name: "Gymnasium Equipments" },
        { name: "Hair Fall Treatments" },
        { name: "Hair Stylists" },
        { name: "Hair Transplantation" },
        { name: "Hair Treatments" },
        { name: "Hall Decorations" },
        { name: "Handicraft Items" },
        { name: "Handlooms" },
        { name: "Hardware And Network Training Institutes" },
        { name: "Hardware And Networking" },
        { name: "Hardware Stores" },
        { name: "Hardware Tools" },
        { name: "Hardwood Flooring" },
        { name: "HD Cameras" },
        { name: "Health" },
        { name: "Health Clubs" },
        { name: "Hearse Services" },
        { name: "Heavy Vehicle Dealers" },
        { name: "Helmet Dealers" },
        { name: "Hispanic Churches" },
        { name: "Home Appliances" },
        { name: "Home Builders" },
        { name: "Home Delivery Restaurants" },
        { name: "Home Furniture" },
        { name: "Home Needs" },
        { name: "Home Theater Systems" },
        { name: "Homeopathy Clinics" },
        { name: "Homeopathy Medicines" },
        { name: "Hosiery Store" },
        { name: "Hospitals" },
        { name: "Hotels" },
        { name: "House Painters" },
        { name: "Housekeeping Services" },
        { name: "Hr Consultancies" },
        { name: "Hydraulic & Pulley Equipment Dealers" },
        { name: "Hydrochloric Acid Dealers" },
        { name: "Hypermarkets" },
        { name: "IB Schools" },
        { name: "Ice Cream & Dessert Parlors" },
        { name: "ICSE Schools" },
        { name: "IGCSE Schools" },
        { name: "Immigration Consultants" },
        { name: "Income Tax Offices" },
        { name: "Industrial Bearing Dealers" },
        { name: "Industrial Belt Dealers" },
        { name: "Industrial Burner Dealers" },
        { name: "Industrial Chemical Dealers" },
        { name: "Industrial Electronic Components Dealers" },
        { name: "Industrial Equipments" },
        { name: "Industrial Fan Dealers" },
        { name: "Industrial Fire Extinguisher Dealers" },
        { name: "industrial machine dealers" },
        { name: "Industrial Safety Equipment Dealers" },
        { name: "Industrial Spring Dealers" },
        { name: "Industrial Trolleys Manufacturer" },
        { name: "Innerwear And Loungewear" },
        { name: "Institute Of Hotel Management" },
        { name: "Insurance Agents" },
        { name: "Interior Design Courses" },
        { name: "Interior Designers" },
        { name: "Internet Service Providers" },
        { name: "Inverters" },
        { name: "Investment Advisors" },
        { name: "Irrigation Equipment Dealers" },
        { name: "ITI Training" },
        { name: "Jain Temples" },
        { name: "Jeans" },
        { name: "Jewellery" },
        { name: "Jewellery Box Manufacturers" },
        { name: "Journalism Training Institutes" },
        { name: "Juice Centre" },
        { name: "Junior Colleges" },
        { name: "Kalyana Mandapam" },
        { name: "Kennels" },
        { name: "Kitchen & Dining" },
        { name: "Kitchen Storage Containers" },
        { name: "Lab Equipment And Chemical Suppliers" },
        { name: "Labor Contractors" },
        { name: "Laboratories" },
        { name: "Ladies Bags & Purses" },
        { name: "Ladies Dresses" },
        { name: "Laminate Flooring" },
        { name: "Language Training Institutes" },
        { name: "Laptop Repair" },
        { name: "Laptops" },
        { name: "Lathe Machine Dealers" },
        { name: "Laundry Services" },
        { name: "Law Colleges" },
        { name: "Lawn & Garden" },
        { name: "Leather Goods Manufacturer" },
        { name: "Legal & Financial Services" },
        { name: "Legal Services" },
        { name: "Libraries" },
        { name: "Lifestyle Accessories" },
        { name: "Lightings" },
        { name: "Living Room Furniture" },
        { name: "Loan Agencies" },
        { name: "Loan Agents" },
        { name: "Local Government Offices" },
        { name: "Locks" },
        { name: "Lodges" },
        { name: "Logistic Companies" },
        { name: "Logistics Services" },
        { name: "Lounges" },
        { name: "Luxury Hotels" },
        { name: "Maggam Job Works" },
        { name: "Makeup Artists" },
        { name: "Manufacturer of Power Generators" },
        { name: "Marriage Bureaus" },
        { name: "Marriage Halls" },
        { name: "Mass Communication & Journalism Colleges" },
        { name: "Matching Centres" },
        { name: "Maternity Hospitals" },
        { name: "Mattresses" },
        { name: "Meat & Poultry Shops" },
        { name: "Media Advertising" },
        { name: "Medical Coding Training Institutes" },
        { name: "Medical Colleges" },
        { name: "Medical Equipments" },
        { name: "Medical Stockings" },
        { name: "Meditation Centres" },
        { name: "Mehandi Artists" },
        { name: "Mennonite Churches" },
        { name: "Mens Hostels" },
        { name: "Mesh Dealers" },
        { name: "Metal Industries" },
        { name: "Methodist Churches" },
        { name: "Metro Rail Stations" },
        { name: "Microbreweries" },
        { name: "Microwave Repairs" },
        { name: "Military Recruiting Offices" },
        { name: "Milk & Milk Products" },
        { name: "Mineral Water Suppliers" },
        { name: "Mobile Phones" },
        { name: "Mobile Repairs" },
        { name: "Mobile Repairs" },
        { name: "Modular Furniture" },
        { name: "Modular Kitchen Dealers" },
        { name: "Money Transfer Agencies" },
        { name: "Montessori Training Institutes" },
        { name: "Moravian Churches" },
        { name: "Morgues Services" },
        { name: "Mormon Churches" },
        { name: "Mosques" },
        { name: "Motor Driving Schools" },
        { name: "Mould Dies Manufacturer" },
        { name: "Moving Media Ads" },
        { name: "Mp3 Players" },
        { name: "MS Pipe Dealer" },
        { name: "Multispecialty Hospitals" },
        { name: "Museums" },
        { name: "Music Academies" },
        { name: "Musical Instruments" },
        { name: "Mutton Shops" },
        { name: "Natural Flooring" },
        { name: "Nature Cure Centers" },
        { name: "Naturopathy" },
        { name: "Network Securities" },
        { name: "Networking Devices" },
        { name: "New Age Churches" },
        { name: "Newspaper Ads" },
        { name: "NGO Clubs" },
        { name: "NGOs & Social Service Organisations" },
        { name: "Night Clubs" },
        { name: "Night Life" },
        { name: "Night Wears" },
        { name: "Nitric Acid Dealers" },
        { name: "Notary Services" },
        { name: "Number Plate Manufacturers" },
        { name: "Nursing Colleges" },
        { name: "Nutritional Supplement Dealers" },
        { name: "Office Furniture" },
        { name: "Offices" },
        { name: "Offset Printers" },
        { name: "Old Age Homes" },
        { name: "Old Cut Notes Exchange Services" },
        { name: "Online Classes" },
        { name: "Optics & Eyewear" },
        { name: "Organ Donation Centres" },
        { name: "Orphanages & Shelters" },
        { name: "Orthodox Churches" },
        { name: "Other Vehicles" },
        { name: "Outdoor Advertising" },
        { name: "Outdoor Catering Services" },
        { name: "Outdoor Furniture" },
        { name: "Overseas Education Consultants" },
        { name: "Oxygen Concentrators" },
        { name: "Oxygen Gas Dealers" },
        { name: "P R P Hair Treatments" },
        { name: "Packers And Movers" },
        { name: "Packing Machine Manufacturers" },
        { name: "Painters" },
        { name: "Painting Suppliers" },
        { name: "Pan Shops" },
        { name: "Pants" },
        { name: "Paper Rolls Manufacturers" },
        { name: "Paper Stores" },
        { name: "Parks" },
        { name: "Part Time Jobs Consultancies" },
        { name: "Party Halls" },
        { name: "Passport Offices" },
        { name: "Pawn Brokers" },
        { name: "Pcs & Desktops" },
        { name: "Pedicure & Manicure" },
        { name: "Pen Stores" },
        { name: "Pentecostal Churches" },
        { name: "Perforated Sheet Manufacturers" },
        { name: "Perfumes" },
        { name: "Personal Fitness Trainers" },
        { name: "Personality Development Training Institutes" },
        { name: "Pest Control Services" },
        { name: "Pet Shops" },
        { name: "Pets" },
        { name: "PG Colleges" },
        { name: "Pharmaceutical Companies" },
        { name: "Pharmaceutical Packaging Material Dealers" },
        { name: "Pharmacies" },
        { name: "Pharmacy Colleges" },
        { name: "Photo Frames" },
        { name: "Photo Studios" },
        { name: "Photocopiers" },
        { name: "Photographers" },
        { name: "Photography Training Institutes" },
        { name: "physiotherapist" },
        { name: "Physiotherapy Clinics" },
        { name: "Piercing" },
        { name: "Pilot Training Institutes" },
        { name: "Pipe Dealers" },
        { name: "Pizza Restaurants" },
        { name: "Placement Consultants" },
        { name: "Plants" },
        { name: "Plastic & Disposable Items" },
        { name: "Plastic Injection Moulding Machine Dealer" },
        { name: "Plastic Products Manufacturers" },
        { name: "Play Schools" },
        { name: "Play Stations" },
        { name: "Playground Equipments" },
        { name: "Playgrounds" },
        { name: "Plumbers" },
        { name: "Plumbing" },
        { name: "Plywood & Laminates" },
        { name: "Police Stations" },
        { name: "Political Party Offices" },
        { name: "Pollution Inspection Stations" },
        { name: "Polymers & Asbestos Products Dealer" },
        { name: "Polytechnic Colleges" },
        { name: "Pork Shops" },
        { name: "Post Offices" },
        { name: "Power Generator Suppliers" },
        { name: "Power Stations" },
        { name: "Power Tools Dealers" },
        { name: "Presbyterian Churches" },
        { name: "Printed Circuit Board Dealers" },
        { name: "Printers" },
        { name: "Printing & Stationaries" },
        { name: "Printing Machines" },
        { name: "Printing Materials" },
        { name: "Printing Press" },
        { name: "Professional Services" },
        { name: "Professionals" },
        { name: "Project Management Training Institutes" },
        { name: "Projectors" },
        { name: "Promotional Products" },
        { name: "Property Consultants" },
        { name: "Property Dealers" },
        { name: "Protestant Churches" },
        { name: "Public Safety Offices" },
        { name: "Pubs" },
        { name: "Pumps & Controllers" },
        { name: "Pundits" },
        { name: "PVC Pipe Dealer" },
        { name: "Quaker Churches" },
        { name: "Quick Bites" },
        { name: "Radio Jockey Training Institutes" },
        { name: "Radio Stations" },
        { name: "Radium Works" },
        { name: "Railings" },
        { name: "Railway Cargo Agents" },
        { name: "Railway Stations" },
        { name: "Ready Made Garments" },
        { name: "Ready Mix Concrete" },
        { name: "Real Estate" },
        { name: "Real Estate Agents" },
        { name: "Real Estate Developers" },
        { name: "Real Estate Loans & Mortgages" },
        { name: "Recording Studios" },
        { name: "Reformed Churches" },
        { name: "Refrigerator Repair" },
        { name: "Refrigerators" },
        { name: "Registry Offices" },
        { name: "Rehabilitation Centres" },
        { name: "Religion" },
        { name: "Research Institutes" },
        { name: "Residential Designers" },
        { name: "Resins & Chemicals Manufacturer" },
        { name: "Resorts" },
        { name: "Restaurant Test" },
        { name: "Restaurants" },
        { name: "RO Water Purifier" },
        { name: "Road Cargo Agents" },
        { name: "Robotics Engineering" },
        { name: "Robotics Training Institutes" },
        { name: "Roofing Sheets" },
        { name: "RTA Offices" },
        { name: "Rubber Oil Seals Dealer" },
        { name: "Rubber Product Dealer" },
        { name: "Rubber Product Manufacturers" },
        { name: "Rubber Stamps" },
        { name: "Rudraksha" },
        { name: "Russian Orthodox Churches" },
        { name: "Sand Materials" },
        { name: "Sandals & Floaters" },
        { name: "Sanitaryware & Bathroom Accessories" },
        { name: "Sarees & Blouses" },
        { name: "Scalp Treatments" },
        { name: "School District Offices" },
        { name: "School For Mentally Challenged" },
        { name: "Scrap Dealers" },
        { name: "Screen Printers" },
        { name: "Sea Cargo Agents" },
        { name: "Seat Cover & Rexine Works" },
        { name: "Security Guard Services" },
        { name: "Security Services" },
        { name: "Security Systems" },
        { name: "Seeds" },
        { name: "SelfDefence Training Services" },
        { name: "Servers" },
        { name: "Service Centres" },
        { name: "Serviced Apartments" },
        { name: "Seventh-Day Adventist Churches" },
        { name: "Sewing Machine Dealers" },
        { name: "Share Brokers" },
        { name: "Shipping Companies" },
        { name: "Shirts" },
        { name: "Shoes" },
        { name: "Shopping Malls" },
        { name: "Shorts & Cargo" },
        { name: "Sign Boards" },
        { name: "Signage" },
        { name: "Singing Classes" },
        { name: "Skin Care Clinics" },
        { name: "Snooker Parlours" },
        { name: "Socks" },
        { name: "Sofa Sets" },
        { name: "Software & IT Services" },
        { name: "Software Certifications" },
        { name: "Software Dealers" },
        { name: "Software Development" },
        { name: "Software Training Institutes" },
        { name: "Solar Products Manufacturers" },
        { name: "Sound And Lighting On Hire" },
        { name: "Sound Systems" },
        { name: "Spa & Saloon" },
        { name: "Spare Part Dealers" },
        { name: "Spare Parts & Accessories" },
        { name: "Speakers" },
        { name: "Spiritual And Pooja Accessories" },
        { name: "Spiritual Centres" },
        { name: "Spoken English Institutes" },
        { name: "Sports" },
        { name: "Sports Academies" },
        { name: "Sports Clubs" },
        { name: "Sports Equipments" },
        { name: "Sports Stores" },
        { name: "Sports Wear" },
        { name: "Sports, Entertainment & Hobbies" },
        { name: "Stadiums" },
        { name: "Stage Decorations" },
        { name: "Stainless Steel Pipe Dealer" },
        { name: "Stamp Papers" },
        { name: "Standees & Demo Tents" },
        { name: "State Board Schools" },
        { name: "State Government Offices" },
        { name: "Stationaries" },
        { name: "Stationary Stores" },
        { name: "Stations" },
        { name: "Steel Wires & Ropes Manufacturers" },
        { name: "Stem Cell Banking" },
        { name: "Stock Brokers" },
        { name: "Studios" },
        { name: "Study Hall Centre" },
        { name: "Sub-Registrar Offices" },
        { name: "Suitings & Shirtings" },
        { name: "Suits And Blazers" },
        { name: "Sulphuric Acid Dealers" },
        { name: "Sunglasses" },
        { name: "Super Specialty Hospitals" },
        { name: "Supermarkets" },
        { name: "Surgical Instruments" },
        { name: "Sweet Shops" },
        { name: "Swimming Pools" },
        { name: "Table Accessories" },
        { name: "Tailoring Materials" },
        { name: "Tailors" },
        { name: "Tailors & Designers" },
        { name: "Take Away Restaurants" },
        { name: "Tattoo Makers" },
        { name: "Telecommunications" },
        { name: "Television Installation" },
        { name: "Televisions" },
        { name: "Temples" },
        { name: "Tent Houses" },
        { name: "Textiles" },
        { name: "Theaters" },
        { name: "Theme Parks" },
        { name: "Thermocol Dealers" },
        { name: "Ticketing" },
        { name: "Tiles" },
        { name: "Timber Depot" },
        { name: "Tmt Iron & Steel Bars" },
        { name: "Tours And Travels" },
        { name: "Toy Shops" },
        { name: "Trading Consultants" },
        { name: "Training Institutes" },
        { name: "Transportation" },
        { name: "Travel Agencies" },
        { name: "Travel Goods" },
        { name: "Travel Services" },
        { name: "Trophy & Momento Dealers" },
        { name: "Trousers" },
        { name: "T-Shirts" },
        { name: "Tuitions" },
        { name: "Tv Accessories" },
        { name: "TV Studio" },
        { name: "Two Wheelers Dealers" },
        { name: "Two Wheelers Service Centres" },
        { name: "Typing Institutes" },
        { name: "Tyre Dealers" },
        { name: "Unani Treatment" },
        { name: "Underground Stations" },
        { name: "Uniforms" },
        { name: "Unitarian Universalist Churches" },
        { name: "United Churches Of Christ" },
        { name: "Unity Churches" },
        { name: "Universities" },
        { name: "UPS" },
        { name: "UPSC & IAS Coaching Centres" },
        { name: "Used Auto Dealers" },
        { name: "Used Bike Dealers" },
        { name: "Used Cars Dealers" },
        { name: "Utensils" },
        { name: "UV Water Purifier" },
        { name: "Valve Dealer" },
        { name: "Vegetables" },
        { name: "Vehicle Glass Dealers" },
        { name: "Vehicle On Hire" },
        { name: "Vending Machine Manufacturer" },
        { name: "Veterinary Hospitals" },
        { name: "Veterinary Medicines" },
        { name: "Video Editing Studios" },
        { name: "Video Gaming Centres" },
        { name: "Videographers" },
        { name: "Vineyard Churches" },
        { name: "Vinyl Flooring" },
        { name: "Vocational Colleges" },
        { name: "Wall Papers" },
        { name: "Washing Machine Repair" },
        { name: "Washing Machines" },
        { name: "Water Cooler Suppliers" },
        { name: "Water Parks" },
        { name: "Water Purifier Dealers" },
        { name: "Water Purifier Repairs" },
        { name: "Water Softeners" },
        { name: "Water Suppliers" },
        { name: "Water Tank Suppliers" },
        { name: "Waterproofing" },
        { name: "Waterproofing Materials" },
        { name: "Weather Stations" },
        { name: "Web Designing Companies" },
        { name: "Web Hosting Companies" },
        { name: "Wedding & Events" },
        { name: "Wedding Bands" },
        { name: "Wedding Cards" },
        { name: "Wedding Catering Services" },
        { name: "Wedding Decorations" },
        { name: "Wedding Planners" },
        { name: "Weight Loss & Gain Centres" },
        { name: "Welding Equipment" },
        { name: "Welfare Offices" },
        { name: "Wesleyan Churches" },
        { name: "Wet Grinder Dealers" },
        { name: "Wine Shops" },
        { name: "Winter Wear" },
        { name: "Wire Mesh Dealers" },
        { name: "Womens Hostels" },
        { name: "Wooden Flooring" },
        { name: "Wrist Watch Repairs and Services" },
        { name: "Wrist Watches" },
        { name: "Xerox Shops" },
        { name: "Yoga Centres" },
        { name: "Zoo Parks" },
        { name: "Zumba Fitness" },
    ]


export default objectarray;